name: publish
on:
  push:
    branches: master
jobs:
  publish-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/cache@master
        with:
          path: |
            node_modules
            packages/core/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: make publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
