name: test
on: push
jobs:
  test-node-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/cache@master
        with:
          path: |
            node_modules
            packages/core/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
      - run: yarn bootstrap
      - run: yarn lerna exec yarn tsc
      - run: yarn lerna run test
